from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "docs/planning/BLACKSMITH_PHASE1_UNIFIED_IMPLEMENTATION_CONTRACT_20260828.md"
CORE_CANON = ROOT / "docs/planning/BLACKSMITH_CORE_SIMPLIFICATION_CANON_20260825.md"
HANDOFF = ROOT / "docs/operations/BS-OPS-20260825-08_SESSION_HANDOFF_CORE_SIMPLIFICATION.md"
WEAPON_KEYWORD_DECISION = ROOT / "docs/decisions/BS-ENHANCE-20260828-34_WEAPON_KEYWORD_OWNERSHIP.md"
HISTORICAL_PRECISION = ROOT / "docs/planning/BLACKSMITH_R2_PRECISION_ENHANCEMENT_METHOD_AND_CATALYST_STRUCTURE_CANON_2026.md"
HISTORICAL_CATALYST = ROOT / "docs/planning/BLACKSMITH_R2_CATALYST_AFFIX_SEED_EVOLUTION_AND_MUTATION_CANON_2026.md"
SUPERSEDED_INCIDENT = ROOT / "docs/operations/BS-INC-20260828-39_CATALYST_TAG_AND_PRECISION_METHOD_OWNERSHIP.md"
INCIDENT = ROOT / "docs/operations/BS-INC-20260828-40_CATALYST_METHOD_TAG_RESOLUTION.md"


def require_tokens(tokens: tuple[str, ...]) -> None:
    text = CONTRACT.read_text(encoding="utf-8")
    missing = [token for token in tokens if token not in text]
    assert not missing, f"{CONTRACT.name}: missing {missing}"


def main() -> None:
    require_tokens(
        (
            "CONTRACT_STATUS = CURRENT_CANON_MVP_IMPLEMENTATION_AUTHORIZED",
            "BS-ENHANCE-20260828-34",
            "ITEM_KEYWORD_RECIPIENT = WEAPON_ITEM_ONLY",
            "PLAYER_TITLE_REWARD = FUTURE_CONTENT_NOT_GRANTED_BY_+10",
            "WEAPON_KEYWORD_TAXONOMY = GRADE_KEYWORD / TAG_KEYWORD / EVENT_KEYWORD",
            "TAG_KEYWORD_SOURCE = CATALYST_LINEAGE_AND_PRECISION_METHOD",
            "TAG_KEYWORD_RESOLUTION = CATALYST_LINEAGE_AND_PRECISION_METHOD_GOVERN_TAG_IDENTITY",
            "PRECISION_METHOD_EFFECT_SCOPE = WEAPON_STATS_DURABILITY_AND_TAG_RESOLUTION_CONTEXT",
            "PRECISION_METHOD_TAG_ROLE = TAG_IDENTITY_RESOLUTION",
            "PRECISION_METHOD_CANNOT_AFFECT_GRADE_OR_EVENT_KEYWORD = TRUE",
            "BS-ENHANCE-20260829-37",
            "EMPTY_CATALYST_LINEAGE_BEHAVIOR = BLOCK_BEFORE_COST_OR_ROLL",
            "NO_DEFAULT_LINEAGE = TRUE",
            "PRECISION_SELECTION_PERSISTENCE = ATTEMPT_LOCAL_ONLY",
            "+10_PRECISION_OUTPUT_KEYWORD = TAG_KEYWORD",
            "WEAPON_KEYWORD_CONTENT_ID = DATA_BACKED_FIRST_TAG_CATALOG / BS-ENHANCE-20260829-37",
            "KEYWORD_PRESENTATION = REQUIRED_IN_WORKSHOP_PRECISION_UI / NO_NEW_RASTER",
            "PRIMARY_PLAYABLE_CONTENT = REPEATED_ENHANCEMENT_JUDGMENT_AND_FEEDBACK",
            "PHASE_1_SLICE = +0_TO_+10 / +11_TO_+15 / ONE_SAME_UID_RESULT",
            "CRAFT_FEEDBACK_MILESTONE = EVERY_5_LEVELS",
            "+5 = PRESENTATION_ONLY",
            "+10 = PRESENTATION_PLUS_ONLY_PRECISION_AND_ONE_KEYWORD",
            "NO_PRECISION_OR_AFFIX_OR_PROBABILITY_OR_RESOURCE_RULE_AT_+20_OR_LATER",
            "RETURN_BEAT = ONE_NON_ECONOMIC_WORKSHOP_MOMENT",
            "NO_TIMER / NO_CUSTOMER_MANAGEMENT / NO_SECOND_ITEM / NO_FAKE_DAMAGE",
            "IMPLEMENTATION_DRIFT = LEGACY_MULTI_PRECISION_DATA_AND_NON_VERTICAL_SLICE_MODULES",
            "INCIDENT_ID = BS-OPS-20260828-37",
            "NO_BASE_PROMOTION = PROJECT_SPECIFIC_LEGACY_AND_SLICE_BOUNDARY",
            "P0_IMPLEMENTATION_GUARD = VERTICAL_SLICE_ONLY_CURRENT_CANON",
            "OUT_OF_SCOPE = NEW_ART_ASSET_BATCH / ECONOMY_REBALANCE / MULTI_CUSTOMER_SYSTEM / RELEASE_WORK",
            "TEST_ORDER = RED_CONTRACTS -> GREEN_MINIMUM_FLOW -> REFACTOR_LEGACY_BOUNDARIES",
            "HUMAN_PLAYTEST = DEFERRED_BY_USER / NOT_RUN",
            "PHASE_2_ENTRY = SATISFIED_BY_CURRENT_CANON_MVP_ACTIVE_BY_USER_DECLARATION_20260826",
        )
    )
    locator = "BLACKSMITH_PHASE1_UNIFIED_IMPLEMENTATION_CONTRACT_20260828.md"
    assert locator in CORE_CANON.read_text(encoding="utf-8"), "core canon must locate the unified contract"
    assert locator in HANDOFF.read_text(encoding="utf-8"), "handoff must locate the unified contract"
    decision_text = WEAPON_KEYWORD_DECISION.read_text(encoding="utf-8")
    require_decision_tokens = (
        "STATUS = USER_APPROVED_CURRENT",
        "FIELD_OWNER = WEAPON_KEYWORD_OWNERSHIP",
        "ITEM_KEYWORD_RECIPIENT = WEAPON_ITEM_ONLY",
        "ITEM_KEYWORD_MACHINE_OWNER = CATALYST_AFFIX",
        "PLAYER_TITLE_REWARD = FUTURE_CONTENT_NOT_GRANTED_BY_+10",
        "WEAPON_KEYWORD_TAXONOMY = GRADE_KEYWORD / TAG_KEYWORD / EVENT_KEYWORD",
        "TAG_KEYWORD_SOURCE = CATALYST_LINEAGE_AND_PRECISION_METHOD",
        "TAG_KEYWORD_RESOLUTION = CATALYST_LINEAGE_AND_PRECISION_METHOD_GOVERN_TAG_IDENTITY",
        "PRECISION_METHOD_EFFECT_SCOPE = WEAPON_STATS_DURABILITY_AND_TAG_RESOLUTION_CONTEXT",
        "PRECISION_METHOD_TAG_ROLE = TAG_IDENTITY_RESOLUTION",
        "PRECISION_METHOD_CANNOT_AFFECT_GRADE_OR_EVENT_KEYWORD = TRUE",
        "EMPTY_CATALYST_LINEAGE_BEHAVIOR = BLOCK_BEFORE_COST_OR_ROLL",
        "GRADE_KEYWORD_MACHINE_OWNER = GRADE_AFFIX",
        "TAG_KEYWORD_MACHINE_OWNER = CATALYST_AFFIX",
        "EVENT_KEYWORD_MACHINE_OWNER = CHRONICLE_AFFIX",
        "+10_PRECISION_OUTPUT_KEYWORD = TAG_KEYWORD",
        "WEAPON_KEYWORD_CONTENT_ID = DATA_BACKED_FIRST_TAG_CATALOG / BS-ENHANCE-20260829-37",
        "HISTORICAL_FIXTURE_OR_CUSTOMER_EPITHET_REUSE = FORBIDDEN",
    )
    missing_decision = [token for token in require_decision_tokens if token not in decision_text]
    assert not missing_decision, f"{WEAPON_KEYWORD_DECISION.name}: missing {missing_decision}"
    taxonomy_token = "WEAPON_KEYWORD_TAXONOMY = GRADE_KEYWORD / TAG_KEYWORD / EVENT_KEYWORD"
    assert taxonomy_token in CORE_CANON.read_text(encoding="utf-8"), "core canon must mirror weapon keyword taxonomy"
    assert taxonomy_token in HANDOFF.read_text(encoding="utf-8"), "handoff must preserve weapon keyword taxonomy"
    ownership_tokens = (
        "TAG_KEYWORD_SOURCE = CATALYST_LINEAGE_AND_PRECISION_METHOD",
        "TAG_KEYWORD_RESOLUTION = CATALYST_LINEAGE_AND_PRECISION_METHOD_GOVERN_TAG_IDENTITY",
        "PRECISION_METHOD_EFFECT_SCOPE = WEAPON_STATS_DURABILITY_AND_TAG_RESOLUTION_CONTEXT",
        "PRECISION_METHOD_TAG_ROLE = TAG_IDENTITY_RESOLUTION",
        "PRECISION_METHOD_CANNOT_AFFECT_GRADE_OR_EVENT_KEYWORD = TRUE",
        "EMPTY_CATALYST_LINEAGE_BEHAVIOR = BLOCK_BEFORE_COST_OR_ROLL",
    )
    for document in (CORE_CANON, HANDOFF):
        document_text = document.read_text(encoding="utf-8")
        missing = [token for token in ownership_tokens if token not in document_text]
        assert not missing, f"{document.name}: missing {missing}"
    for document in (HISTORICAL_PRECISION, HISTORICAL_CATALYST):
        document_text = document.read_text(encoding="utf-8")
        assert "CURRENT_OVERRIDE_BS-ENHANCE-20260828-34" in document_text, f"{document.name}: missing current override"
    assert "SUPERSEDED_BY_BS-INC-20260828-40" in SUPERSEDED_INCIDENT.read_text(encoding="utf-8")
    incident_text = INCIDENT.read_text(encoding="utf-8")
    assert "NO_BASE_PROMOTION = PROJECT_SPECIFIC_WEAPON_KEYWORD_OWNERSHIP" in incident_text
    assert "data-backed, localized first-slice keyword" not in CONTRACT.read_text(encoding="utf-8")
    assert "non-placeholder weapon keyword" not in CONTRACT.read_text(encoding="utf-8")
    print("phase1 unified implementation contract: PASS")


if __name__ == "__main__":
    main()
