from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DECISION = "BS-OPS-20260811-03"
PHASE_BLOCK = """<!-- BS_OPS_20260811_03_PHASE_C_ENTRY -->
> **PLANNING_COMPLETE / BS-OPS-20260811-03 / PHASE_B_FINAL_REVIEW_COMPLETE / PHASE_C_ENTRY_APPROVED**
>
> 사용자가 `기획 완료`를 명시했다. R3–R7 기획 배치는 승인된 9/10에서 닫으며, 승인되지 않은 Decision10을 만들지 않는다. 이미 승인된 정본 구현만 Phase C로 진입하고 신규 제품 범위는 별도 Decision이 필요하다.
>
> `PLANNING_COMPLETE: USER_DECLARED` / `R3_R7_PLANNING_BATCH: CLOSED_AT_9_OF_10` / `PHASE_B_FINAL_REVIEW: COMPLETE`
>
> `PRODUCT_IMPLEMENTATION: PHASE_C_ENTRY_APPROVED_WITHIN_EXISTING_APPROVED_CANON`
>
> `TASK3_IMPLEMENTATION: NOT_SEPARATELY_APPROVED`
>
> `P0_LOCAL_EXECUTOR_BOOTSTRAP: REQUIRED_BEFORE_PERSISTENT_GODOT_AUTHORING`
>
> `IMAGE_GENERATION: DEFERRED_BY_USER`
>
> 전용 로컬 실행환경: self-contained Godot 4.7.1 (`_sc_`) → HiGodot HTTP `8006` / WS `9506` → `C:\\Users\\user\\.codex-blacksmith` → exact Blacksmith 경로에서 Codex. 포트/process 존재는 readiness PASS가 아니며 Codex 내부 fresh HiGodot receipt 전 persistent mutation 금지.

"""


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    (ROOT / path).write_text(text, encoding="utf-8", newline="\n")


def insert_after_title(text: str) -> str:
    if "BS_OPS_20260811_03_PHASE_C_ENTRY" in text:
        return text
    first_break = text.find("\n")
    if first_break < 0:
        raise RuntimeError("missing title line")
    return text[: first_break + 1] + "\n" + PHASE_BLOCK + text[first_break + 1 :]


paths = [
    "CURRENT_CONFIRMED_DECISIONS.md",
    "[기획서]/00_프로젝트_허브/ACTIVE_CONTEXT.md",
    "[기획서]/00_프로젝트_허브/START_HERE.md",
    "[기획서]/00_프로젝트_허브/ROADMAP.md",
    "[기획서]/00_프로젝트_허브/DEVELOPMENT_GATES.md",
]

for path in paths:
    text = insert_after_title(read(path))
    write(path, text)

# Convert only the old top routing banner to a historical planning snapshot.
replacements = {
    "CURRENT_CONFIRMED_DECISIONS.md": [
        (
            "<!-- R3_R7_DESIGN_RESUMED -->\n> **R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / R3_R7_9_OF_10 / PLANNING_ONLY**\n>\n> R2 Batch 006과 Task2 기술 폐쇄는 그대로 상속한다. 이번 승인은 R3–R7 기획 재개이며 Task3 또는 일반 제품 구현 승인으로 확대하지 않는다.",
            "<!-- R3_R7_PLANNING_BATCH_HISTORICAL_CLOSED_AT_9_OF_10 -->\n> **HISTORICAL_R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / R3_R7_9_OF_10 / PLANNING_ONLY**\n>\n> 아래 블록은 `기획 완료` 이전 R3–R7 9/10 planning snapshot이다. 당시 `PRODUCT_IMPLEMENTATION: BLOCKED` / `TASK3_IMPLEMENTATION: NOT_APPROVED`였으며, 현재 Phase C gate는 위 `BS-OPS-20260811-03`이 소유한다.",
        ),
    ],
    "[기획서]/00_프로젝트_허브/ACTIVE_CONTEXT.md": [
        (
            "<!-- R3_R7_DESIGN_RESUMED -->\n> **R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY**",
            "<!-- R3_R7_PLANNING_BATCH_HISTORICAL_CLOSED_AT_9_OF_10 -->\n> **HISTORICAL_R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY**",
        ),
        ("CURRENT_STAGE: R3_R7_DESIGN_ACTIVE", "CURRENT_STAGE: PHASE_C_IMPLEMENTATION_ENTRY"),
        ("WORK_MODE: PLAN_REVIEW", "WORK_MODE: BUILD_REVIEW"),
        ("PRODUCT_IMPLEMENTATION: BLOCKED", "HISTORICAL_R3_PRODUCT_IMPLEMENTATION: BLOCKED\nPRODUCT_IMPLEMENTATION: PHASE_C_ENTRY_APPROVED_WITHIN_EXISTING_APPROVED_CANON"),
        ("TASK3_IMPLEMENTATION: NOT_APPROVED", "HISTORICAL_R3_TASK3_IMPLEMENTATION: NOT_APPROVED\nTASK3_IMPLEMENTATION: NOT_SEPARATELY_APPROVED"),
        ("NEW_PRODUCT_SCOPE: USER_DECISION_REQUIRED", "NEW_PRODUCT_SCOPE: USER_DECISION_REQUIRED_BEYOND_EXISTING_APPROVED_CANON"),
    ],
    "[기획서]/00_프로젝트_허브/START_HERE.md": [
        (
            "<!-- R3_R7_DESIGN_RESUMED -->\n> **R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY**",
            "<!-- R3_R7_PLANNING_BATCH_HISTORICAL_CLOSED_AT_9_OF_10 -->\n> **HISTORICAL_R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY**",
        ),
        ("CURRENT_STAGE: R3_R7_DESIGN_ACTIVE", "CURRENT_STAGE: PHASE_C_IMPLEMENTATION_ENTRY"),
        ("WORK_MODE: PLAN_REVIEW", "WORK_MODE: BUILD_REVIEW"),
        ("PRODUCT_IMPLEMENTATION: BLOCKED", "HISTORICAL_R3_PRODUCT_IMPLEMENTATION: BLOCKED\nPRODUCT_IMPLEMENTATION: PHASE_C_ENTRY_APPROVED_WITHIN_EXISTING_APPROVED_CANON"),
        ("TASK3_IMPLEMENTATION: NOT_APPROVED", "HISTORICAL_R3_TASK3_IMPLEMENTATION: NOT_APPROVED\nTASK3_IMPLEMENTATION: NOT_SEPARATELY_APPROVED"),
        ("NEW_PRODUCT_SCOPE: USER_DECISION_REQUIRED", "NEW_PRODUCT_SCOPE: USER_DECISION_REQUIRED_BEYOND_EXISTING_APPROVED_CANON"),
    ],
    "[기획서]/00_프로젝트_허브/ROADMAP.md": [
        (
            "<!-- R3_R7_DESIGN_RESUMED -->\n> **R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY**",
            "<!-- R3_R7_PLANNING_BATCH_HISTORICAL_CLOSED_AT_9_OF_10 -->\n> **HISTORICAL_R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY**",
        ),
        ("CURRENT_STAGE: R3_R7_DESIGN_ACTIVE", "CURRENT_STAGE: PHASE_C_IMPLEMENTATION_ENTRY"),
        ("CURRENT_STAGE_STATUS: R3_R7_9_OF_10_USER_APPROVED_PLANNING_ONLY", "CURRENT_STAGE_STATUS: PLANNING_COMPLETE_PHASE_B_REVIEW_COMPLETE_PHASE_C_ENTRY_APPROVED"),
        ("PRODUCT_IMPLEMENTATION: BLOCKED", "HISTORICAL_R3_PRODUCT_IMPLEMENTATION: BLOCKED\nPRODUCT_IMPLEMENTATION: PHASE_C_ENTRY_APPROVED_WITHIN_EXISTING_APPROVED_CANON"),
        ("TASK3_IMPLEMENTATION: NOT_APPROVED", "HISTORICAL_R3_TASK3_IMPLEMENTATION: NOT_APPROVED\nTASK3_IMPLEMENTATION: NOT_SEPARATELY_APPROVED"),
    ],
    "[기획서]/00_프로젝트_허브/DEVELOPMENT_GATES.md": [
        (
            "<!-- R3_R7_DESIGN_RESUMED -->\n> **R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY / PRODUCT_BLOCKED**",
            "<!-- R3_R7_PLANNING_BATCH_HISTORICAL_CLOSED_AT_9_OF_10 -->\n> **HISTORICAL_R3_R7_DESIGN_ACTIVE / BS-CONTENT-20260811-09 / GLADIATOR_02_KYLE_VETERAN_CONTINUITY_APPROVED / PLANNING_ONLY / PRODUCT_BLOCKED**",
        ),
        ("CURRENT_STAGE: R3_R7_DESIGN_ACTIVE", "CURRENT_STAGE: PHASE_C_IMPLEMENTATION_ENTRY"),
        ("R3_R7_DESIGN_GATE: USER_APPROVED_PLANNING_ONLY", "R3_R7_DESIGN_GATE: USER_APPROVED_PLANNING_COMPLETE_CLOSED_AT_9_OF_10"),
        ("CODEX_IMPLEMENTATION_GATE: VERTICAL_SLICE_APPROVED_SCOPED_ONLY_TASK2_COMPLETE", "CODEX_IMPLEMENTATION_GATE: PHASE_C_ENTRY_APPROVED_EXISTING_CANON_ONLY_P0_BOOTSTRAP_FIRST"),
        ("PRODUCT_IMPLEMENTATION: BLOCKED", "HISTORICAL_R3_PRODUCT_IMPLEMENTATION: BLOCKED\nPRODUCT_IMPLEMENTATION: PHASE_C_ENTRY_APPROVED_WITHIN_EXISTING_APPROVED_CANON"),
        ("GENERAL_PRODUCT_IMPLEMENTATION: BLOCKED", "GENERAL_PRODUCT_IMPLEMENTATION: APPROVED_WITHIN_EXISTING_CANON_NEW_SCOPE_REQUIRES_DECISION"),
        ("TASK3_IMPLEMENTATION: NOT_APPROVED", "HISTORICAL_R3_TASK3_IMPLEMENTATION: NOT_APPROVED\nTASK3_IMPLEMENTATION: NOT_SEPARATELY_APPROVED"),
        ("ENTRY_STATE_GATE: PASS_R3_R7_PLANNING_ONLY_PRODUCT_SCOPE_STILL_REQUIRED", "ENTRY_STATE_GATE: PASS_PLANNING_COMPLETE_PHASE_C_EXISTING_CANON_P0_BOOTSTRAP_REQUIRED"),
        ("NEW_PRODUCT_SCOPE: USER_DECISION_REQUIRED", "NEW_PRODUCT_SCOPE: USER_DECISION_REQUIRED_BEYOND_EXISTING_APPROVED_CANON"),
        ("IMAGE_PRODUCT_GATE: BLOCKED_NOT_PRODUCT_READY", "IMAGE_PRODUCT_GATE: DEFERRED_BY_USER"),
    ],
}

for path, pairs in replacements.items():
    text = read(path)
    for old, new in pairs:
        if old not in text:
            raise RuntimeError(f"expected anchor missing in {path}: {old[:80]!r}")
        text = text.replace(old, new, 1)
    write(path, text)

# Add a current phase YAML to CURRENT where its operating state block is the owner.
current_path = "CURRENT_CONFIRMED_DECISIONS.md"
current = read(current_path)
old = "R3_R7_DESIGN_STATE: R3_R7_DESIGN_ACTIVE\nR3_R7_APPROVAL_COUNTER: 9/10\nR3_R7_CURRENT_DECISION: BS-CONTENT-20260811-09\nNEW_PRODUCT_SCOPE: NEW_PRODUCT_SCOPE_USER_DECISION_REQUIRED\nTASK3_IMPLEMENTATION: NOT_APPROVED\nPRODUCT_IMPLEMENTATION: BLOCKED"
new = "R3_R7_DESIGN_STATE: R3_R7_PLANNING_BATCH_CLOSED_AT_9_OF_10\nR3_R7_APPROVAL_COUNTER: 9/10\nR3_R7_CURRENT_DECISION: BS-CONTENT-20260811-09\nPLANNING_COMPLETE: USER_DECLARED\nR3_R7_PLANNING_BATCH: CLOSED_AT_9_OF_10\nPHASE_B_FINAL_REVIEW: COMPLETE\nLOCAL_EXECUTOR_DECISION: BS-OPS-20260811-03\nP0_LOCAL_EXECUTOR_BOOTSTRAP: REQUIRED_BEFORE_PERSISTENT_GODOT_AUTHORING\nNEW_PRODUCT_SCOPE: NEW_PRODUCT_SCOPE_USER_DECISION_REQUIRED_BEYOND_EXISTING_APPROVED_CANON\nHISTORICAL_R3_TASK3_IMPLEMENTATION: NOT_APPROVED\nTASK3_IMPLEMENTATION: NOT_SEPARATELY_APPROVED\nHISTORICAL_R3_PRODUCT_IMPLEMENTATION: BLOCKED\nPRODUCT_IMPLEMENTATION: PHASE_C_ENTRY_APPROVED_WITHIN_EXISTING_APPROVED_CANON\nIMAGE_GENERATION: DEFERRED_BY_USER"
if old not in current:
    raise RuntimeError("CURRENT operating-state anchor missing")
current = current.replace(old, new, 1)
write(current_path, current)

# Recompute operating-health digest for CURRENT_CONFIRMED_DECISIONS.md.
health_path = ROOT / "docs/PROJECT_OPERATING_HEALTH.json"
health = json.loads(health_path.read_text(encoding="utf-8"))
digest = hashlib.sha256((ROOT / current_path).read_bytes()).hexdigest()
found = False
for item in health.get("evidence", {}).get("operating", []):
    if item.get("id") == "BS-CURRENT-DECISIONS":
        item["sha256"] = digest
        found = True
        break
if not found:
    raise RuntimeError("BS-CURRENT-DECISIONS health evidence missing")
health_path.write_text(json.dumps(health, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("BS-OPS-20260811-03 phase C authority materialized")
print("CURRENT sha256", digest)
